// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/codemk8/zong/models"
)

// NewSelfCheckParams creates a new SelfCheckParams object
// with the default values initialized.
func NewSelfCheckParams() SelfCheckParams {
	var ()
	return SelfCheckParams{}
}

// SelfCheckParams contains all the bound params for the self check operation
// typically these are obtained from a http.Request
//
// swagger:parameters selfCheck
type SelfCheckParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*System Spec
	  Required: true
	  In: body
	*/
	Body *models.System
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *SelfCheckParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.System
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
