// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SelfCheckMethodNotAllowedCode is the HTTP code returned for type SelfCheckMethodNotAllowed
const SelfCheckMethodNotAllowedCode int = 405

/*SelfCheckMethodNotAllowed Invalid input

swagger:response selfCheckMethodNotAllowed
*/
type SelfCheckMethodNotAllowed struct {
}

// NewSelfCheckMethodNotAllowed creates SelfCheckMethodNotAllowed with default headers values
func NewSelfCheckMethodNotAllowed() *SelfCheckMethodNotAllowed {
	return &SelfCheckMethodNotAllowed{}
}

// WriteResponse to the client
func (o *SelfCheckMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
