// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SelfCheckHandlerFunc turns a function with the right signature into a self check handler
type SelfCheckHandlerFunc func(SelfCheckParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SelfCheckHandlerFunc) Handle(params SelfCheckParams) middleware.Responder {
	return fn(params)
}

// SelfCheckHandler interface for that can handle valid self check params
type SelfCheckHandler interface {
	Handle(SelfCheckParams) middleware.Responder
}

// NewSelfCheck creates a new http.Handler for the self check operation
func NewSelfCheck(ctx *middleware.Context, handler SelfCheckHandler) *SelfCheck {
	return &SelfCheck{Context: ctx, Handler: handler}
}

/*SelfCheck swagger:route GET / API selfCheck

Status of System

*/
type SelfCheck struct {
	Context *middleware.Context
	Handler SelfCheckHandler
}

func (o *SelfCheck) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSelfCheckParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
