// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*StatusDefault successful operation

swagger:response statusDefault
*/
type StatusDefault struct {
	_statusCode int
}

// NewStatusDefault creates StatusDefault with default headers values
func NewStatusDefault(code int) *StatusDefault {
	if code <= 0 {
		code = 500
	}

	return &StatusDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the status default response
func (o *StatusDefault) WithStatusCode(code int) *StatusDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the status default response
func (o *StatusDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *StatusDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
