// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetAPIDefault successful operation

swagger:response getApiDefault
*/
type GetAPIDefault struct {
	_statusCode int
}

// NewGetAPIDefault creates GetAPIDefault with default headers values
func NewGetAPIDefault(code int) *GetAPIDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAPIDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get API default response
func (o *GetAPIDefault) WithStatusCode(code int) *GetAPIDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get API default response
func (o *GetAPIDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetAPIDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
