// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Zong
Zong Restful Server

Terms Of Service:

https://codemk8.io/terms/


    Schemes:
      http
    Host: localhost
    BasePath: /v2
    Version: 1.0.0
    License: MIT https://opensource.org/licenses/MIT
    Contact: <help@codemk8.io>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
