// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// System system
// swagger:model System
type System struct {

	// name
	Name string `json:"name,omitempty"`

	// size
	// Required: true
	Size *int64 `json:"size"`

	// explain...
	Status string `json:"status,omitempty"`
}

// Validate validates this system
func (m *System) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSize(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *System) validateSize(formats strfmt.Registry) error {

	if err := validate.Required("size", "body", m.Size); err != nil {
		return err
	}

	return nil
}

var systemTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["available","pending"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		systemTypeStatusPropEnum = append(systemTypeStatusPropEnum, v)
	}
}

const (
	// SystemStatusAvailable captures enum value "available"
	SystemStatusAvailable string = "available"
	// SystemStatusPending captures enum value "pending"
	SystemStatusPending string = "pending"
)

// prop value enum
func (m *System) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, systemTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *System) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *System) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *System) UnmarshalBinary(b []byte) error {
	var res System
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
